### PR TITLE
01b	added some new terms

### PR DESCRIPTION
**Pull request by tacurran**
https://github.com/NoMoKeTo/c3nav/commit/3cbb90fc401fc7e13bbc4a6c35ab4fed9e07f308

### CODE REVIEW

**Comment by codingcatgirl** [comment]
Sorry, but you can't just rename Foyer with Lobby everywhere. Those are not the official english titles. 

Also, your commit is just word by wort translating the names of assemblies which is not usefull at all – you can't translate names, noone will recognize them.

Freifunk → Free Signal – are you serious right now? https://en.wikipedia.org/wiki/Freifunk

Sorry, but no.

**Comment by tacurran** [comment]
Sorry, my mistake. It was a quick global change...  NP.  Good product

**Comment by codingcatgirl** [comment]
yeah… „product“. please inform yourself about an event before proposing bullshit changes as literally translating chaospatinnen, geheimorga or freifunkt.

**Comment by tacurran** [comment]
All good. Will work on my Irish humour as well...

**Pull request closed without merging**
